"""Creacion inicial de tablas

Revision ID: 9f41a2232e43
Revises: 
Create Date: 2026-09-23 19:39:45.434619

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9f41a2232e43'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Platillos',
    sa.Column('idPlatillo', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('precio', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('idPlatillo')
    )
    op.create_index(op.f('ix_Platillos_idPlatillo'), 'Platillos', ['idPlatillo'], unique=False)
    op.create_table('Usuarios',
    sa.Column('idUsuario', sa.Integer(), nullable=False),
    sa.Column('usuario', sa.String(length=50), nullable=False),
    sa.Column('clave', sa.String(length=255), nullable=False),
    sa.Column('rol', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('idUsuario'),
    sa.UniqueConstraint('usuario')
    )
    op.create_index(op.f('ix_Usuarios_idUsuario'), 'Usuarios', ['idUsuario'], unique=False)
    op.create_table('Reservas',
    sa.Column('idReserva', sa.Integer(), nullable=False),
    sa.Column('Usuarios_idUsuario', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=True),
    sa.Column('fecha', sa.Date(), nullable=True),
    sa.Column('hora', sa.Time(), nullable=True),
    sa.Column('descripcion', sa.String(length=255), nullable=True),
    sa.Column('estado', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['Usuarios_idUsuario'], ['Usuarios.idUsuario'], ),
    sa.PrimaryKeyConstraint('idReserva')
    )
    op.create_index(op.f('ix_Reservas_idReserva'), 'Reservas', ['idReserva'], unique=False)
    op.create_table('Ventas',
    sa.Column('idVenta', sa.Integer(), nullable=False),
    sa.Column('Reservas_idReserva', sa.Integer(), nullable=False),
    sa.Column('Reservas_Usuarios_IdUsuario', sa.Integer(), nullable=True),
    sa.Column('fecha', sa.Date(), nullable=True),
    sa.Column('hora', sa.Time(), nullable=True),
    sa.Column('rucDni', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['Reservas_Usuarios_IdUsuario'], ['Usuarios.idUsuario'], ),
    sa.ForeignKeyConstraint(['Reservas_idReserva'], ['Reservas.idReserva'], ),
    sa.PrimaryKeyConstraint('idVenta')
    )
    op.create_index(op.f('ix_Ventas_idVenta'), 'Ventas', ['idVenta'], unique=False)
    op.create_table('DetalleVentas',
    sa.Column('idDetalleVenta', sa.Integer(), nullable=False),
    sa.Column('Ventas_idVenta', sa.Integer(), nullable=False),
    sa.Column('Platillos_idPlatillo', sa.Integer(), nullable=False),
    sa.Column('cantidad', sa.Integer(), nullable=False),
    sa.Column('subtotal', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['Platillos_idPlatillo'], ['Platillos.idPlatillo'], ),
    sa.ForeignKeyConstraint(['Ventas_idVenta'], ['Ventas.idVenta'], ),
    sa.PrimaryKeyConstraint('idDetalleVenta')
    )
    op.create_index(op.f('ix_DetalleVentas_idDetalleVenta'), 'DetalleVentas', ['idDetalleVenta'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_DetalleVentas_idDetalleVenta'), table_name='DetalleVentas')
    op.drop_table('DetalleVentas')
    op.drop_index(op.f('ix_Ventas_idVenta'), table_name='Ventas')
    op.drop_table('Ventas')
    op.drop_index(op.f('ix_Reservas_idReserva'), table_name='Reservas')
    op.drop_table('Reservas')
    op.drop_index(op.f('ix_Usuarios_idUsuario'), table_name='Usuarios')
    op.drop_table('Usuarios')
    op.drop_index(op.f('ix_Platillos_idPlatillo'), table_name='Platillos')
    op.drop_table('Platillos')
    # ### end Alembic commands ###
